# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCRUDNotepad():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cRUDNotepad(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1440, 869)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    time.sleep(1)
    self.driver.find_element(By.ID, "password").send_keys("1234")
    time.sleep(1)
    self.driver.find_element(By.ID, "submit").click()
    time.sleep(1)
    self.driver.get("http://127.0.0.1:5000/notepad/create")
    time.sleep(1)
    self.driver.find_element(By.ID, "title").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "title").send_keys("Prueba Selenium IDE")
    time.sleep(1)
    self.driver.find_element(By.ID, "body").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "body").send_keys("Prueba Selenium IDE")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "submit").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Prueba Selenium IDE").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Back to Notepads").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "title").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "title").send_keys(" Editada")
    time.sleep(1)
    self.driver.find_element(By.ID, "body").send_keys(" Editada")
    time.sleep(1)
    self.driver.find_element(By.ID, "submit").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Prueba Selenium IDE Editada").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Back to Notepads").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(1)